# Generated by Django 5.0.6 on 2024-05-16 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_staff', models.CharField(max_length=255)),
                ('pisitionID', models.IntegerField(default=5, verbose_name='ID - position')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('date_of_employment', models.DateTimeField(auto_now_add=True, verbose_name='Date of employment')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salary worker')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cstaff.position', verbose_name='Position in work')),
            ],
        ),
    ]
