# Generated by Django 5.0.6 on 2024-06-29 10:33

import cstaff.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_staff', models.CharField(max_length=255, verbose_name='Position Title')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StaffGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_staff', models.IntegerField(verbose_name='Group')),
            ],
            options={
                'verbose_name': 'Staff Group',
                'verbose_name_plural': 'Staff Groups',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_employment', models.DateTimeField(auto_now_add=True, verbose_name='Date of Employment')),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Salary')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Image profil')),
                ('position', models.ForeignKey(blank=True, default=cstaff.models.get_default_position, on_delete=django.db.models.deletion.CASCADE, to='cstaff.position', verbose_name='Position')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, default=cstaff.models.get_default_group, on_delete=django.db.models.deletion.CASCADE, to='cstaff.staffgroup', verbose_name='Group Staff')),
            ],
            options={
                'verbose_name': 'Staff Member',
                'verbose_name_plural': 'Staff Members',
                'ordering': ['user'],
            },
        ),
    ]
