# Generated by Django 5.0.6 on 2024-05-26 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_staff', models.CharField(max_length=255, verbose_name='Position Title')),
                ('positionID', models.IntegerField(default=5, verbose_name='Position ID')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
                'ordering': ['positionID'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Name')),
                ('date_of_employment', models.DateTimeField(auto_now_add=True, verbose_name='Date of Employment')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Salary')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Image profil')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cstaff.position', verbose_name='Position')),
            ],
            options={
                'verbose_name': 'Staff Member',
                'verbose_name_plural': 'Staff Members',
                'ordering': ['name'],
            },
        ),
    ]
