# Generated by Django 5.0.6 on 2024-05-16 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cstaff', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['position_staff'], 'verbose_name': 'Position', 'verbose_name_plural': 'Positions'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['name'], 'verbose_name': 'Staff Member', 'verbose_name_plural': 'Staff Members'},
        ),
        migrations.RemoveField(
            model_name='position',
            name='pisitionID',
        ),
        migrations.AddField(
            model_name='position',
            name='positionID',
            field=models.IntegerField(default=5, verbose_name='Position ID'),
        ),
        migrations.AlterField(
            model_name='position',
            name='position_staff',
            field=models.CharField(max_length=255, verbose_name='Position Title'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='date_of_employment',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date of Employment'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cstaff.position', verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salary'),
        ),
    ]
