# Generated by Django 5.0.6 on 2024-05-23 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cstaff', '0006_staff_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['positionID'], 'verbose_name': 'Position', 'verbose_name_plural': 'Positions'},
        ),
        migrations.AlterField(
            model_name='staff',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
